language: python
sudo: false
before_script:
  - pip install -r requirements_dev.txt
script:
  - isort -rc -c tests defusedcsv
  - flake8 tests defusedcsv
  - coverage run -m py.test tests && codecov
matrix:
  include:
    - python: 3.4
    - python: 3.5
    - python: 3.6
